---

- hosts: 10.0.0.210

  tasks:
  - name: Installation du serveur Apache et PHP
    yum:
     name: "{{ item }}"
     state: present
    loop:
      - httpd
      - php

  - name: Arret du service nginx
    systemd:
     name: nginx
     state: stopped

  - name: DÃ©marrage du serveur apache
    systemd:
     name: httpd
     state: started
    
